name: Deploy

on:
  push:
    branches: [master]

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    needs: [run-tests]
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set environment
        run: |
            echo "ENV=prod"                                                 >> $GITHUB_ENV
            echo "COMPOSE_FILE=docker-compose.prod.yml"                     >> $GITHUB_ENV
          echo "REPOSITORY_NAME_LOWER=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Frontend: build
      - uses: oven-sh/setup-bun@v2

      - name: Install frontend deps
        working-directory: ./
        run: bun install --frozen-lockfile

      - name: Build frontend
        working-directory: ./
        run: bun run build

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        run: |
          docker build \
            --build-arg API_NAME=${{ vars.API_NAME }} \
            --build-arg DOTNET_VERSION=9.0 \
            -t ${{ env.REPOSITORY_NAME_LOWER }}-backend:${{ env.ENV }} \
            -t ${{ env.REPOSITORY_NAME_LOWER }}-backend:${{ github.sha }} \
            ./backend
          docker push ${{ env.REPOSITORY_NAME_LOWER }}:${{ env.ENV }}
          docker push ${{ env.REPOSITORY_NAME_LOWER }}:${{ github.sha }}

      - name: Pull new images
        run: |
          docker-compose \
            -f /var/www/RESources-Relationnelles/docker-compose.yml \
            -f /var/www/RESources-Relationnelles/${{ env.COMPOSE_FILE }} \
            pull backend

      - name: Restart services
        run: |
          docker-compose \
            -f /var/www/RESources-Relationnelles/docker-compose.yml \
            -f /var/www/RESources-Relationnelles/${{ env.COMPOSE_FILE }} \
            up -d --no-build backend

      - name: Clean up
        run: docker image prune -f